### ISSUE TITLE
Error when compiling the package

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/robot_interfaces#103]
When compiling this package on my Ubuntu 18.04 machine using ROS dashing I am getting the error:

```
--- stderr: robot_interfaces                                                                                                                  
CMake Error at CMakeLists.txt:69 (ament_export_targets):
  Unknown CMake command "ament_export_targets".
```

Any idea?

\cc @MaximilienNaveau

**Comment by MaximilienNaveau** [comment]
Delete this package from your workspace it's no longer a dependency of BLMC_ROBOTS

**Comment by luator** [comment]
Sorry, I wasn't aware that others are using this package as well.  I moved to Ubuntu 20.04 (and thus ROS Foxy) for the robot_interfaces/fingers project. In Foxy the name of `ament_export_interfaces` was changed to `ament_export_targets` (the old name still works but gives a deprecation warning).  In case you want to use the package but need to stick with 18.04 you can simply rename it back to `ament_export_interfaces`.

**Comment by jviereck** [comment]
Hi, 

thanks for the replies. Deleting the package works for us.

Closing the issue.
