### ISSUE TITLE
SensorBackend should use non-real-time thread

### ISSUE THREAD

**Issue by luator** [open-dynamic-robot-initiative/robot_interfaces#40]
To my understanding, the cameras will anyway not work in real time, so there is probably no use of running the `SensorBackend` in a real-time thread. On the other hand, it is probably beneficial to keep the number of real-time threads low, so it would be better to use a standard non-real-time thread here.

https://github.com/open-dynamic-robot-initiative/robot_interfaces/blob/1fa5daa15c99d2a47e7d9f106e33bd8011d54127/include/robot_interfaces/sensors/sensor_backend.hpp#L49

**Comment by shrutij01** [comment]
Yes, thanks, am looking into this.
