### ISSUE TITLE
where to get appropriate signal handler package and corresponding signal_handlerConfig.cmake file?

### ISSUE THREAD

**Issue by Akshay-9416** [open-dynamic-robot-initiative/robot_interfaces#88]
I am trying to build robot interfaces and i am unable to full fill this dependency, can someone please help me with this.

![image](https://user-images.githubusercontent.com/60077708/98350288-245d7600-2041-11eb-8405-da879b38e453.png)

Thank you

**Comment by luator** [comment]
Sorry for the very late response, I missed this issue and just saw it now... I assume that it is not relevant anymore by now but just in case:

- The `signal_handler` package is here: https://github.com/MPI-IS/signal_handler
- If you are using `treep` to get the packages, you should update the treep configuration and re-clone the project.  Then the signal_handler package (and other new dependencies) should be included.

**Comment by luator** [comment]
I'm closing this now, assuming the issue is resolved.  Feel free to reopen, in case it is not.
